version: '3.7'

services:
  geth-explorer:
    container_name: tlx-explorer
    image: alethio/ethereum-lite-explorer
    environment:
      APP_NODE_URL: "${TESTNET_RPC_HTTP}://${TESTNET_HOST}:8545"
    ports:
      - "4000:80"

